/*If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.*/

//array that stores the values of multiples generated by the first for loop
var multiples = [];
//loops through numbers 0-1000 and finds numbers that are multiples of 3 or 5 
for (var i = 0; i < 1000; i++) {
	if (i % 3 === 0 || i % 5 === 0) {
		multiples[multiples.length] = i;
	}
}

//function calculates the total of all entries generated in the first for loop.
function addMultiples(list) {
	var total = 0;
for (var i = 0; i < list.length; i++) {
		total += list[i];
	}
	return total;
}

console.log(addMultiples(multiples));